name: Build and test

on:
    # Only on pushes to main or one of the release branches we build on push
    push:
        branches:
            - main
        tags:
    # Build pull requests
    pull_request:

jobs:
    test:
        strategy:
            matrix:
                py:
                    - "3.7"
                    - "3.8"
                    - "3.9"
                    - "3.10"
                    - "3.11"
                os:
                    - "ubuntu-latest"
                    - "macos-latest"
                architecture:
                    - x64
                    - x86
                pg-version:
                    - "12"
                    - "14"
                exclude:
                    # Linux and macOS don't have x86 python
                    - os: "ubuntu-latest"
                      architecture: x86
                    - os: "macos-latest"
                      architecture: x86
        name: "Python ${{ matrix.py }}-${{ matrix.architecture }} + PG ${{ matrix.pg-version }} on ${{ matrix.os }}"
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.py }}
                  architecture: ${{ matrix.architecture }}
            - uses: ankane/setup-postgres@v1
              with:
                  postgres-version: ${{ matrix.pg-version }}
            - run: pip install tox
            - name: Running tox
              run: tox -e py
    coverage:
        runs-on: ubuntu-latest
        name: Validate coverage
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.7"
                  architecture: x64

            - run: pip install tox
            - run: tox -e py37,coverage
    lint:
        runs-on: ubuntu-latest
        name: Lint the package
        steps:
            - uses: actions/checkout@v3
            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.7"
                  architecture: x64
            - run: pip install tox
            - run: tox -e lint
